/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AdminDiscordId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "ConfigTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DealsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DiscordClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HotUKDealsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SessionSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Site": {
      "type": "sst.aws.React"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}